version: "3.9"

services:
  chat-server:
    build:
      context: ./server
    container_name: messencharles-server
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped
    environment:
      - DB_FILE=/data/chat.db
    volumes:
      - chat-data:/data

  chat-client:
    build:
      context: ./client
    container_name: messencharles-client
    ports:
      - "127.0.0.1:3001:8080"
    depends_on:
      - chat-server

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: messencharles-cloudflared
    command: tunnel --no-autoupdate --url http://chat-client:8080
    depends_on:
      - chat-client
    restart: unless-stopped

volumes:
  chat-data:
